### ISSUE TITLE
We need users to have the possibility to add requests via a form on our website

### ISSUE THREAD

**Issue by DragosPetria** [komakio/app#81]
Currently, people can only add requests via the app. We would need them to be able to add them via web form to accomodate less tech-friendly people.

Form must include:
- First name
- Last name
- Phone number
- Address (translated into geolocation)
- Agree to privacy policy and terms of service

PLUS
Captcha - safety
IP - we need to capture this to be able to block abusers.

**Comment by Mokto** [comment]
Done through https://github.com/komakio/website/commit/06ee4bec69e413c88f0e3a39927a02360f6f8f50
